import { motion } from 'framer-motion';

const TermsOfService = () => {
  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl mx-auto">
      <div className="glass-panel p-6 md:p-10">
        <h1 className="text-2xl md:text-4xl font-bold mb-6">Terms of Service</h1>
        
        <div className="space-y-6 text-gray-300 text-sm md:text-base leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p className="text-gray-400">By accessing and using AI Interviewer, you agree to be bound by these Terms of Service. If you do not agree, please discontinue use of the platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">2. Service Description</h2>
            <p className="text-gray-400">AI Interviewer provides AI-powered mock interview practice, resume analysis, and performance tracking. The platform is intended for educational and practice purposes only.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">3. User Responsibilities</h2>
            <p className="text-gray-400">You are responsible for maintaining the confidentiality of your account credentials. You agree not to misuse the service, including attempting to overload or hack the platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">4. AI-Generated Content</h2>
            <p className="text-gray-400">Interview questions and feedback are generated by AI (Groq). While we strive for accuracy, AI-generated content may occasionally contain errors. The platform should not be the sole basis for career decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">5. Intellectual Property</h2>
            <p className="text-gray-400">The AI Interviewer platform, its design, and code are the intellectual property of the creator. Your interview responses remain your own property.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">6. Limitation of Liability</h2>
            <p className="text-gray-400">AI Interviewer is provided "as is" without warranties. We are not liable for any damages arising from the use of this platform, including but not limited to career outcomes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">7. Contact</h2>
            <p className="text-gray-400">Questions about these terms can be directed to us via <a href="https://www.linkedin.com/in/sitaramkum/" target="_blank" rel="noopener noreferrer" className="text-primary-400 hover:underline">LinkedIn</a>.</p>
          </section>

          <p className="text-gray-500 text-xs pt-4 border-t border-white/10">Last updated: May 2026</p>
        </div>
      </div>
    </motion.div>
  );
};

export default TermsOfService;
